# Generated by Django 5.2.5 on 2025-08-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gfg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
